version: 2.1

jobs:

  create-infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: deploying infra
          command: |
            aws cloudformation deploy \
            --template-file ec2.yml \
            --stack-name CICD

workflows:

  Infra-workflow:
    jobs:
      - create-infra
      