version: 2.1

jobs:

  create-infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: deploying infra
          command: |
            aws cloudformation deploy \
            --template-file ec2.yml \
            --stack-name CICD
      - run:
          name: send the ip to the inventory
          command: |
            sh ./get-ip.sh
            cat inventory.txt
            pwd
      - save_cache:
          paths:
            - inventory.txt
          key: ec2-ipp
              
  configure-infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["d5:35:24:ab:6c:22:9e:66:48:16:7e:dd:46:41:7d:59"]
      - restore_cache:
          keys:
            - ec2-ipp
      - run: cat inventory.txt
      - run:
          name: installing asnible
          command: |
            apk add --update ansible
      - run:
          name: run ansible-playbook
          command: |
            ansible-playbook -i inventory.txt cicd_playbook.yml


workflows:

  Infra-workflow:
    jobs:
      - create-infra
      - configure-infra:
          requires:
            - create-infra
      